---
name: build
on: [deployment, push]

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [centos7, centos7jp, centos8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tomonorimatsumura/ansible-test
          dockerfile: ${{ matrix.base-image }}/Dockerfile
          tags: ${{ matrix.base-image }}-latest

  github-container-registory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [centos7, centos7jp, centos8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT}}
          registry: ghcr.io
          repository: docker-hub-tm/ansible-test/${{ matrix.base-image }}
          dockerfile: ${{ matrix.base-image }}/Dockerfile
          tags: latest

  hadolint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [centos7, centos7jp, centos8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dockerfile lint
        uses: brpaz/hadolint-action@eb9b96be611b84830aa1babacfb7070ecd2a8b1b
        with:
          dockerfile: ${{ matrix.base-image }}/Dockerfile

  find-trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
